name: Snyk Node.js SCAN
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: snyk/actions/setup@master

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Snyk scan custom code
        run: snyk test code
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}